name: gitactiondemo Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Execute jar file
      run: sudo kill -9 'sudo lsof -t -i:9001' & sudo java -jar /home/ubuntu/actions-runner/_work/gitactiondemo/gitactiondemo/target/gitactionsdemoproj-0.0.1-SNAPSHOT.jar &
